/**
 * Regression tests for the OA REST client, focused on the endpoint versions.
 *
 * Zalo splits its OA API across two versions: uploads exist only on v2.0, while
 * messaging lives on v3.0. Posting an upload to v3.0 fails, which is what broke
 * attaching a file to an OA message. These tests pin both halves of that split.
 *
 * `homedir()` is redirected to a temp dir before importing the client so the
 * module-level credentials path never touches the real ~/.zalo-agent.
 */

import { describe, it, before, after, beforeEach } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

const ORIGINAL_HOME = { HOME: process.env.HOME, USERPROFILE: process.env.USERPROFILE };

let home;
let oa;
/** Requests captured from the stubbed HTTP client, oldest first. */
let calls;

/** Queue a canned response for the next request. */
let responses;

function stubClient(url, opts) {
    calls.push({ url, opts });
    const next = responses.shift() || { status: 200, body: JSON.stringify({ error: 0, message: "Success" }) };
    return Promise.resolve({
        status: next.status,
        text: () => Promise.resolve(next.body),
    });
}

before(async () => {
    home = fs.mkdtempSync(join(tmpdir(), "zalo-oa-home-"));
    process.env.HOME = home;
    process.env.USERPROFILE = home;

    fs.mkdirSync(join(home, ".zalo-agent"), { recursive: true });
    fs.writeFileSync(
        join(home, ".zalo-agent", "oa-credentials.json"),
        JSON.stringify({ default: { accessToken: "test-access-token" } }),
    );

    oa = await import("./oa-client.js");
    oa.setHttpClient(stubClient);
});

after(() => {
    oa?.setHttpClient(null);
    for (const [key, value] of Object.entries(ORIGINAL_HOME)) {
        if (value === undefined) delete process.env[key];
        else process.env[key] = value;
    }
    fs.rmSync(home, { recursive: true, force: true });
});

beforeEach(() => {
    calls = [];
    responses = [];
});

/** Write a fixture file inside the temp home and return its path. */
function fixture(name, contents = "fixture-contents") {
    const filePath = join(home, name);
    fs.writeFileSync(filePath, contents);
    return filePath;
}

describe("uploadFile", () => {
    it("posts to the v2.0 upload endpoint, never v3.0", async () => {
        responses.push({ status: 200, body: JSON.stringify({ error: 0, data: { token: "file-token-1" } }) });

        await oa.uploadFile(fixture("report.pdf"));

        assert.equal(calls.length, 1);
        assert.equal(calls[0].url, "https://openapi.zalo.me/v2.0/oa/upload/file");
        assert.doesNotMatch(calls[0].url, /v3\.0/);
    });

    it("sends a POST with the access token and a multipart body", async () => {
        responses.push({ status: 200, body: JSON.stringify({ error: 0, data: { token: "file-token-1" } }) });

        await oa.uploadFile(fixture("report.pdf"));

        const { opts } = calls[0];
        assert.equal(opts.method, "POST");
        assert.equal(opts.headers.access_token, "test-access-token");
        // Multipart must not carry an explicit JSON content type — the boundary is generated by the client.
        assert.equal(opts.headers["Content-Type"], undefined);
        assert.ok(opts.body instanceof FormData);
    });

    it("names the part by basename and types it from the extension", async () => {
        responses.push({ status: 200, body: JSON.stringify({ error: 0, data: { token: "file-token-1" } }) });

        await oa.uploadFile(fixture("report.pdf"));

        const part = calls[0].opts.body.get("file");
        assert.equal(part.name, "report.pdf");
        assert.equal(part.type, "application/pdf");
    });

    it("rejects an oversize file before making any request", async () => {
        const big = fixture("big.pdf", "x".repeat(5 * 1024 * 1024 + 1));

        await assert.rejects(() => oa.uploadFile(big), /File too large/);
        assert.equal(calls.length, 0);
    });

    it("rejects a missing file before making any request", async () => {
        await assert.rejects(() => oa.uploadFile(join(home, "absent.pdf")), /File not found/);
        assert.equal(calls.length, 0);
    });
});

describe("uploadImage", () => {
    it("posts to the v2.0 upload endpoint, never v3.0", async () => {
        responses.push({ status: 200, body: JSON.stringify({ error: 0, data: { attachment_id: "att-1" } }) });

        await oa.uploadImage(fixture("photo.png"));

        assert.equal(calls[0].url, "https://openapi.zalo.me/v2.0/oa/upload/image");
        assert.doesNotMatch(calls[0].url, /v3\.0/);
    });

    it("types the part from the extension", async () => {
        responses.push({ status: 200, body: JSON.stringify({ error: 0, data: { attachment_id: "att-1" } }) });

        await oa.uploadImage(fixture("photo.png"));

        assert.equal(calls[0].opts.body.get("file").type, "image/png");
    });

    it("enforces the 1MB image cap before making any request", async () => {
        const big = fixture("big.png", "x".repeat(1024 * 1024 + 1));

        await assert.rejects(() => oa.uploadImage(big), /Image too large/);
        assert.equal(calls.length, 0);
    });
});

describe("sendFile", () => {
    it("stays on the v3.0 messaging endpoint", async () => {
        await oa.sendFile("user-1", "file-token-1");

        assert.equal(calls[0].url, "https://openapi.zalo.me/v3.0/oa/message/cs");
        assert.doesNotMatch(calls[0].url, /v2\.0/);
    });

    it("wraps the token in a file attachment payload", async () => {
        await oa.sendFile("user-1", "file-token-1");

        assert.deepEqual(JSON.parse(calls[0].opts.body), {
            recipient: { user_id: "user-1" },
            message: { attachment: { type: "file", payload: { token: "file-token-1" } } },
        });
    });

    it("honours the message type", async () => {
        await oa.sendFile("user-1", "file-token-1", "transaction");

        assert.equal(calls[0].url, "https://openapi.zalo.me/v3.0/oa/message/transaction");
    });

    it("refuses an empty token without making a request", async () => {
        await assert.rejects(() => oa.sendFile("user-1", ""), /Missing file token/);
        assert.equal(calls.length, 0);
    });
});

describe("uploadAndSendFile", () => {
    it("uploads on v2.0 then sends on v3.0 with the returned token", async () => {
        responses.push({ status: 200, body: JSON.stringify({ error: 0, data: { token: "file-token-9" } }) });
        responses.push({ status: 200, body: JSON.stringify({ error: 0, data: { message_id: "msg-1" } }) });

        const { fileToken } = await oa.uploadAndSendFile("user-1", fixture("doc.docx"));

        assert.equal(fileToken, "file-token-9");
        assert.equal(calls.length, 2);
        assert.equal(calls[0].url, "https://openapi.zalo.me/v2.0/oa/upload/file");
        assert.equal(calls[1].url, "https://openapi.zalo.me/v3.0/oa/message/cs");
        assert.equal(JSON.parse(calls[1].opts.body).message.attachment.payload.token, "file-token-9");
    });

    it("keeps the uploaded token on the error when the send fails", async () => {
        responses.push({ status: 200, body: JSON.stringify({ error: 0, data: { token: "file-token-9" } }) });
        responses.push({ status: 200, body: JSON.stringify({ error: -32, message: "Rate limit exceeded" }) });

        const err = await oa.uploadAndSendFile("user-1", fixture("doc.docx")).then(
            () => null,
            (e) => e,
        );

        assert.ok(err, "expected the send failure to propagate");
        assert.match(err.message, /Rate limit exceeded/);
        // The upload already succeeded — the token must survive so the send can be retried.
        assert.equal(err.fileToken, "file-token-9");
    });

    it("fails clearly when the upload returns no token", async () => {
        responses.push({ status: 200, body: JSON.stringify({ error: 0, data: {} }) });

        await assert.rejects(
            () => oa.uploadAndSendFile("user-1", fixture("doc.docx")),
            /Upload succeeded but returned no file token/,
        );
        assert.equal(calls.length, 1, "must not attempt the send");
    });
});

describe("error handling", () => {
    it("surfaces the HTTP status and body for a non-JSON response", async () => {
        responses.push({ status: 502, body: "<html>Bad Gateway</html>" });

        await assert.rejects(
            () => oa.uploadFile(fixture("report.pdf")),
            /OA API returned non-JSON response \(HTTP 502\): <html>Bad Gateway<\/html>/,
        );
    });

    it("surfaces a Zalo error code and message", async () => {
        responses.push({ status: 200, body: JSON.stringify({ error: -201, message: "Data is invalid" }) });

        await assert.rejects(() => oa.uploadFile(fixture("report.pdf")), /OA API error -201: Data is invalid/);
    });
});

describe("upload response extractors", () => {
    it("reads the token from a nested or flat payload", () => {
        assert.equal(oa.extractUploadToken({ data: { token: "t1" } }), "t1");
        assert.equal(oa.extractUploadToken({ token: "t2" }), "t2");
        assert.equal(oa.extractUploadToken({ data: {} }), null);
        assert.equal(oa.extractUploadToken(undefined), null);
    });

    it("reads the attachment_id from a nested or flat payload", () => {
        assert.equal(oa.extractAttachmentId({ data: { attachment_id: "a1" } }), "a1");
        assert.equal(oa.extractAttachmentId({ attachment_id: "a2" }), "a2");
        assert.equal(oa.extractAttachmentId({ data: {} }), null);
        assert.equal(oa.extractAttachmentId(undefined), null);
    });
});
